import { NextResponse } from 'next/server'
import { connectToDatabase } from '@/lib/db'
import Listing from '@/models/Listing'

export async function POST() {
  try {
    await connectToDatabase()

    const total = await Listing.countDocuments({})
    if (total > 0) {
      // Delete all existing listings to reseed
      await Listing.deleteMany({})
    }

    const now = Date.now()
    // Helper to generate sequential phone numbers
    let phoneCounter = 10
    const nextPhone = () => `+91 98765432${phoneCounter++}`
    
    const seedItems = [
      // Notes (5)
      {
        title: 'Advanced Calculus Notes',
        description: 'Comprehensive calculus notes covering derivatives, integrals, and applications. Well-organized handwritten notes.',
        category: 'Notes',
        price: 299,
        originalPrice: 399,
        image: '/calculus-notes-textbook.jpg',
        college: 'IIT Delhi',
        seller: 'Raj Kumar',
        sellerPhone: nextPhone(),
        reviews: 12,
        rating: 4.5,
        postedAt: new Date(now - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Organic Chemistry Study Guide',
        description: 'Detailed study guide with reaction mechanisms and solved problems.',
        category: 'Notes',
        price: 199,
        originalPrice: 0,
        image: '/chemistry-organic-study-guide.jpg',
        college: 'BITS Pilani',
        seller: 'Aditya Patel',
        sellerPhone: nextPhone(),
        reviews: 8,
        rating: 4.3,
        postedAt: new Date(now - 7 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Data Structures Complete Notes',
        description: 'Complete DSA notes with coding examples and algorithm explanations.',
        category: 'Notes',
        price: 249,
        originalPrice: 349,
        image: '/data-structures-algorithms-programming.jpg',
        college: 'IIT Bombay',
        seller: 'Rahul Sharma',
        sellerPhone: nextPhone(),
        reviews: 15,
        rating: 4.7,
        postedAt: new Date(now - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Discrete Mathematics Notes',
        description: 'Complete discrete math notes covering logic, sets, and graphs.',
        category: 'Notes',
        price: 179,
        originalPrice: 0,
        image: '/discrete-mathematics-logic-sets.jpg',
        college: 'Delhi University',
        seller: 'Neha Gupta',
        sellerPhone: nextPhone(),
        reviews: 10,
        rating: 4.4,
        postedAt: new Date(now - 5 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'English Literature Notes - Shakespeare',
        description: 'Complete analysis notes for Shakespeare plays.',
        category: 'Notes',
        price: 149,
        originalPrice: 0,
        image: '/shakespeare-english-literature.jpg',
        college: 'St. Stephen\'s College',
        seller: 'Anjali Mehta',
        sellerPhone: nextPhone(),
        rating: 4.2,
        postedAt: new Date(now - 9 * 24 * 60 * 60 * 1000),
      },

      // Books (5)
      {
        title: 'Introduction to Algorithms',
        description: 'CLRS 3rd Edition. Lightly used, no markings.',
        category: 'Books',
        price: 650,
        originalPrice: 950,
        image: '/data-structures-algorithms-programming.jpg',
        college: 'IIT Bombay',
        seller: 'Campus Seller',
        sellerPhone: nextPhone(),
        rating: 4.7,
        postedAt: new Date(now - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Physics Textbook - Mechanics',
        description: 'Original physics textbook focusing on mechanics. Minimal markings, excellent condition.',
        category: 'Books',
        price: 450,
        originalPrice: 0,
        image: '/physics-mechanics-textbook.jpg',
        college: 'Delhi University',
        seller: 'Priya Singh',
        sellerPhone: nextPhone(),
        rating: 4.8,
        postedAt: new Date(now - 4 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Discrete Mathematics Textbook',
        description: 'Rosen 7th Edition. Minor wear on cover.',
        category: 'Books',
        price: 480,
        originalPrice: 0,
        image: '/discrete-mathematics-logic-sets.jpg',
        college: 'Delhi University',
        seller: 'Campus Seller',
        sellerPhone: nextPhone(),
        rating: 4.6,
        postedAt: new Date(now - 7 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Economics Principles Textbook',
        description: 'Complete microeconomics textbook in great condition.',
        category: 'Books',
        price: 520,
        originalPrice: 750,
        image: '/economics-principles-microeconomics.jpg',
        college: 'Delhi School of Economics',
        seller: 'Amit Verma',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Organic Chemistry Textbook',
        description: 'Complete organic chemistry textbook with reactions.',
        category: 'Books',
        price: 580,
        originalPrice: 850,
        image: '/organic-chemistry-textbook-reactions.jpg',
        college: 'BITS Pilani',
        seller: 'Karan Patel',
        sellerPhone: nextPhone(),
        rating: 4.6,
        postedAt: new Date(now - 6 * 24 * 60 * 60 * 1000),
      },

      // Electronics (5)
      {
        title: 'Scientific Calculator',
        description: 'Casio scientific calculator. 2 years old, excellent condition.',
        category: 'Electronics',
        price: 799,
        originalPrice: 1299,
        image: '/scientific-calculator.jpg',
        college: 'IIT Delhi',
        seller: 'Vikram Rao',
        sellerPhone: nextPhone(),
        rating: 4.6,
        postedAt: new Date(now - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Basic Calculator',
        description: 'TI-30X basic calculator for everyday math.',
        category: 'Electronics',
        price: 299,
        originalPrice: 499,
        image: '/basic-calculator.png',
        college: 'Delhi University',
        seller: 'Sonia Reddy',
        sellerPhone: nextPhone(),
        rating: 4.3,
        postedAt: new Date(now - 5 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Wireless Earbuds',
        description: 'Bluetooth earbuds with case. Good sound quality.',
        category: 'Electronics',
        price: 1299,
        originalPrice: 1999,
        image: '/wireless-earbuds.png',
        college: 'IIT Bombay',
        seller: 'Rohit Kumar',
        sellerPhone: nextPhone(),
        rating: 4.4,
        postedAt: new Date(now - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'USB-C Charging Cable',
        description: 'Fast charging cable, 2m length.',
        category: 'Electronics',
        price: 149,
        originalPrice: 0,
        image: '/placeholder.jpg',
        college: 'BITS Pilani',
        seller: 'Arjun Mehta',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 8 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Portable Power Bank',
        description: '10000mAh power bank with fast charging.',
        category: 'Electronics',
        price: 899,
        originalPrice: 1499,
        image: '/wireless-earbuds-charging-case.png',
        college: 'IIT Madras',
        seller: 'Deepak Sharma',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 4 * 24 * 60 * 60 * 1000),
      },

      // Rental Laptops (5)
      {
        title: 'Dell Laptop Rental - Semester',
        description: 'Dell Inspiron laptop for rent. Good condition, all specs intact.',
        category: 'Rental Laptops',
        price: 3500,
        originalPrice: 0,
        image: '/dell-laptop-computer.jpg',
        college: 'IIT Delhi',
        seller: 'Tech Rentals',
        sellerPhone: nextPhone(),
        rating: 4.7,
        postedAt: new Date(now - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'MacBook Pro Rental - Monthly',
        description: 'MacBook Pro available for monthly rental. Excellent condition.',
        category: 'Rental Laptops',
        price: 5000,
        originalPrice: 0,
        image: '/macbook-pro-laptop.png',
        college: 'IIT Bombay',
        seller: 'Mac Rentals',
        sellerPhone: nextPhone(),
        rating: 4.8,
        postedAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'HP Laptop Rental - Short Term',
        description: 'HP laptop for short-term rental. Perfect for exams.',
        category: 'Rental Laptops',
        price: 2500,
        originalPrice: 0,
        image: '/dell-laptop-computer.jpg',
        college: 'BITS Pilani',
        seller: 'Student Tech',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 6 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Dell XPS Rental',
        description: 'High-performance Dell XPS for semester.',
        category: 'Rental Laptops',
        price: 4500,
        originalPrice: 0,
        image: '/dell-products.png',
        college: 'IIT Madras',
        seller: 'Laptop Hub',
        sellerPhone: nextPhone(),
        rating: 4.6,
        postedAt: new Date(now - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'MacBook Air Rental',
        description: 'Lightweight MacBook Air for students.',
        category: 'Rental Laptops',
        price: 4000,
        originalPrice: 0,
        image: '/silver-macbook-on-desk.png',
        college: 'Ashoka University',
        seller: 'Campus Laptops',
        sellerPhone: nextPhone(),
        rating: 4.7,
        postedAt: new Date(now - 5 * 24 * 60 * 60 * 1000),
      },

      // Lab Uniforms (5)
      {
        title: 'Lab Coat - White',
        description: 'Professional white lab coat. Medium size.',
        category: 'Lab Uniforms',
        price: 599,
        originalPrice: 899,
        image: '/lab-coat-apron-uniform.jpg',
        college: 'IIT Delhi',
        seller: 'Lab Wear',
        sellerPhone: nextPhone(),
        rating: 4.6,
        postedAt: new Date(now - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Lab Apron Set',
        description: 'Complete lab apron set with safety features.',
        category: 'Lab Uniforms',
        price: 449,
        originalPrice: 699,
        image: '/lab-coat-apron-uniform.jpg',
        college: 'BITS Pilani',
        seller: 'Safety Gear',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 4 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Lab Safety Gloves',
        description: 'Chemical-resistant lab gloves. Box of 50.',
        category: 'Lab Uniforms',
        price: 199,
        originalPrice: 0,
        image: '/placeholder.jpg',
        college: 'IIT Bombay',
        seller: 'Lab Supplies Co',
        sellerPhone: nextPhone(),
        rating: 4.4,
        postedAt: new Date(now - 7 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Disposable Lab Coveralls',
        description: 'One-time use lab coveralls. Box of 10.',
        category: 'Lab Uniforms',
        price: 249,
        originalPrice: 0,
        image: '/lab-coat-apron-uniform.jpg',
        college: 'Delhi University',
        seller: 'Professional Lab',
        sellerPhone: nextPhone(),
        rating: 4.3,
        postedAt: new Date(now - 10 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Lab Shoes - Slip Resistant',
        description: 'Anti-slip lab shoes for safety.',
        category: 'Lab Uniforms',
        price: 799,
        originalPrice: 1299,
        image: '/placeholder.jpg',
        college: 'IIT Madras',
        seller: 'Safety First',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 8 * 24 * 60 * 60 * 1000),
      },

      // Stationery (5)
      {
        title: 'Notebook Set - 5 Books',
        description: 'A4 size notebooks, college ruled. Perfect for classes.',
        category: 'Stationery',
        price: 249,
        originalPrice: 349,
        image: '/stationery-pens-notebooks.jpg',
        college: 'IIT Delhi',
        seller: 'Stationery Corner',
        sellerPhone: nextPhone(),
        rating: 4.6,
        postedAt: new Date(now - 2 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Gel Pen Set - 12 Colors',
        description: 'Smooth writing gel pens, assorted colors.',
        category: 'Stationery',
        price: 99,
        originalPrice: 149,
        image: '/stationery-pens-notebooks.jpg',
        college: 'Delhi University',
        seller: 'Pen World',
        sellerPhone: nextPhone(),
        rating: 4.7,
        postedAt: new Date(now - 1 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Highlighter Set - 6 Colors',
        description: 'Fluorescent highlighters for note taking.',
        category: 'Stationery',
        price: 79,
        originalPrice: 0,
        image: '/stationery-pens-notebooks.jpg',
        college: 'BITS Pilani',
        seller: 'Study Supplies',
        sellerPhone: nextPhone(),
        rating: 4.4,
        postedAt: new Date(now - 5 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'A4 Sticky Notes Pack',
        description: 'Colorful sticky notes for reminders. 4 packs.',
        category: 'Stationery',
        price: 59,
        originalPrice: 0,
        image: '/stationery-pens-notebooks.jpg',
        college: 'IIT Bombay',
        seller: 'Office Depot',
        sellerPhone: nextPhone(),
        rating: 4.3,
        postedAt: new Date(now - 6 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Stationery Organizer Bag',
        description: 'Pencil case with compartments for all supplies.',
        category: 'Stationery',
        price: 149,
        originalPrice: 249,
        image: '/stationery-flatlay.png',
        college: 'St. Stephen\'s College',
        seller: 'Campus Store',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 4 * 24 * 60 * 60 * 1000),
      },

      // ID Card Tags (4)
      {
        title: 'ID Card Holder Pack (5 pcs)',
        description: 'Durable plastic holders with clips.',
        category: 'ID Card Tags',
        price: 149,
        originalPrice: 0,
        image: '/id-card-holder-tags.jpg',
        college: "St. Stephen's College",
        seller: 'Campus Essentials',
        sellerPhone: nextPhone(),
        rating: 4.3,
        postedAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Retractable ID Badge Reels (3 pcs)',
        description: 'Smooth retractable reels, assorted colors.',
        category: 'ID Card Tags',
        price: 129,
        originalPrice: 0,
        image: '/placeholder.jpg',
        college: 'Ashoka University',
        seller: 'Campus Essentials',
        sellerPhone: nextPhone(),
        rating: 4.2,
        postedAt: new Date(now - 6 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Transparent ID Pouches (10 pcs)',
        description: 'Waterproof pouches for ID cards.',
        category: 'ID Card Tags',
        price: 99,
        originalPrice: 0,
        image: '/placeholder.jpg',
        college: 'NIT Bangalore',
        seller: 'Campus Essentials',
        sellerPhone: nextPhone(),
        rating: 4.1,
        postedAt: new Date(now - 9 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Lanyard with Name Tag (Blue)',
        description: 'Comfortable lanyard with printed name tag.',
        category: 'ID Card Tags',
        price: 79,
        originalPrice: 0,
        image: '/placeholder.jpg',
        college: 'IIT Madras',
        seller: 'Campus Essentials',
        sellerPhone: nextPhone(),
        rating: 4.0,
        postedAt: new Date(now - 11 * 24 * 60 * 60 * 1000),
      },

      // Lab Equipment (5)
      {
        title: 'Microscope Slides Set (50 pcs)',
        description: 'Sealed set with cover slips.',
        category: 'Lab Equipment',
        price: 599,
        originalPrice: 0,
        image: '/microscope-slides-lab-equipment.jpg',
        college: 'Delhi School of Economics',
        seller: 'Lab Supplies',
        sellerPhone: nextPhone(),
        rating: 4.7,
        postedAt: new Date(now - 4 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Classic Microscope',
        description: 'Student microscope with magnification lenses.',
        category: 'Lab Equipment',
        price: 3499,
        originalPrice: 4999,
        image: '/classic-microscope.png',
        college: 'IIT Delhi',
        seller: 'Lab Equipment Co',
        sellerPhone: nextPhone(),
        rating: 4.6,
        postedAt: new Date(now - 7 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Safety Goggles',
        description: 'Anti-fog, chemical-resistant lab goggles.',
        category: 'Lab Equipment',
        price: 199,
        originalPrice: 0,
        image: '/placeholder.jpg',
        college: 'BITS Pilani',
        seller: 'Lab Supplies',
        sellerPhone: nextPhone(),
        rating: 4.5,
        postedAt: new Date(now - 12 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Digital pH Meter',
        description: 'Portable pH tester for lab use.',
        category: 'Lab Equipment',
        price: 699,
        originalPrice: 0,
        image: '/placeholder.jpg',
        college: 'IIT Bombay',
        seller: 'Lab Supplies',
        sellerPhone: nextPhone(),
        rating: 4.3,
        postedAt: new Date(now - 14 * 24 * 60 * 60 * 1000),
      },
      {
        title: 'Lab Glassware Set',
        description: 'Complete set of beakers, flasks, and test tubes.',
        category: 'Lab Equipment',
        price: 1299,
        originalPrice: 1999,
        image: '/placeholder.jpg',
        college: 'IIT Madras',
        seller: 'Scientific Supplies',
        sellerPhone: nextPhone(),
        rating: 4.4,
        postedAt: new Date(now - 8 * 24 * 60 * 60 * 1000),
      },
    ]

    const created = await Listing.insertMany(seedItems)
    return NextResponse.json({ ok: true, message: 'Seed completed', count: created.length })
  } catch (e) {
    return NextResponse.json({ ok: false, error: e.message }, { status: 500 })
  }
}

export async function GET() {
  // Allow GET to trigger seeding as well for convenience
  return POST()
}


