export const colleges = [
  "All Colleges",
  "IIT Delhi",
  "IIT Bombay",
  "IIT Madras",
  "Delhi University",
  "BITS Pilani",
  "NIT Bangalore",
  "Delhi School of Economics",
  "St. Stephen's College",
  "Ashoka University",
]

export const categories = [
  "All",
  "Notes",
  "Books",
  "Electronics",
  "Rental Laptops",
  "Lab Uniforms",
  "Stationery",
  "ID Card Tags",
  "Lab Equipment",
]

export const categoryIcons = {
  All: "📚",
  Notes: "📝",
  Books: "📖",
  Electronics: "⚡",
  "Rental Laptops": "💻",
  "Lab Uniforms": "👔",
  Stationery: "✏️",
  "ID Card Tags": "🏷️",
  "Lab Equipment": "🔬",
}

export const categoryDescriptions = {
  Notes: "Handwritten and typed study notes from various subjects",
  Books: "Textbooks, reference books, and study guides",
  Electronics: "Calculators, headphones, and other electronic devices",
  "Rental Laptops": "Laptops available for semester or short-term rental",
  "Lab Uniforms": "Lab coats, aprons, and other lab safety equipment",
  Stationery: "Notebooks, pens, highlighters, and writing supplies",
  "ID Card Tags": "ID card holders, name tags, and identification accessories",
  "Lab Equipment": "Microscopes, slides, and other laboratory equipment",
}

export const dummyItems = [
  {
    id: 1,
    title: "Advanced Calculus Notes",
    category: "Notes",
    price: 299,
    originalPrice: 399,
    image: "/calculus-notes-textbook.jpg",
    college: "IIT Delhi",
    seller: "Raj Kumar",
    sellerId: 101,
    sellerPhone: "+91 9876543210",
    description:
      "Comprehensive calculus notes covering derivatives, integrals, and applications. Handwritten and well-organized.",
    rating: 4.5,
    reviews: 12,
    quantity: 1,
    postedTime: "12mo ago",
    images: ["/calculus-notes-textbook.jpg"],
  },
  {
    id: 2,
    title: "Physics Textbook - Mechanics",
    category: "Books",
    price: 450,
    originalPrice: 0,
    image: "/physics-mechanics-textbook.jpg",
    college: "Delhi University",
    seller: "Priya Singh",
    sellerId: 102,
    description: "Original physics textbook focusing on mechanics. Minimal markings, in excellent condition.",
    rating: 4.8,
    reviews: 24,
    quantity: 1,
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    images: ["/physics-mechanics-textbook.jpg"],
  },
  {
    id: 3,
    title: "Organic Chemistry Study Guide",
    category: "Notes",
    price: 199,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "BITS Pilani",
    seller: "Aditya Patel",
    sellerId: 103,
    description: "Detailed study guide with reaction mechanisms and solved problems.",
    rating: 4.3,
    reviews: 8,
    quantity: 1,
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 4,
    title: "Data Structures & Algorithms",
    category: "Books",
    price: 550,
    originalPrice: 650,
    image: "/placeholder.svg",
    college: "NIT Bangalore",
    seller: "Vikram Sharma",
    sellerId: 104,
    description: "Complete DSA book with C++ implementations and practice problems.",
    rating: 4.9,
    reviews: 35,
    quantity: 1,
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 5,
    title: "Economics Principles Notes",
    category: "Notes",
    price: 249,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "Delhi School of Economics",
    seller: "Neha Gupta",
    sellerId: 105,
    description: "Comprehensive notes on microeconomics and macroeconomics principles.",
    rating: 4.6,
    reviews: 15,
    quantity: 1,
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 6,
    title: "English Literature - Shakespeare",
    category: "Books",
    price: 350,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "St. Stephen's College",
    seller: "Arjun Verma",
    sellerId: 106,
    description: "Annotated Shakespeare collection with critical analysis.",
    rating: 4.4,
    reviews: 11,
    quantity: 1,
    postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 7,
    title: "Discrete Mathematics Complete Notes",
    category: "Notes",
    price: 279,
    originalPrice: 350,
    image: "/placeholder.svg",
    college: "IIT Bombay",
    seller: "Sneha Desai",
    sellerId: 107,
    description: "Complete discrete math notes with proofs and examples.",
    rating: 4.7,
    reviews: 19,
    quantity: 1,
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 8,
    title: "Organic Chemistry Textbook",
    category: "Books",
    price: 520,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "IIT Madras",
    seller: "Rohan Kapoor",
    sellerId: 108,
    description: "Advanced organic chemistry with reaction mechanisms and synthesis.",
    rating: 4.8,
    reviews: 28,
    quantity: 1,
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 9,
    title: "Dell Laptop - Rental",
    category: "Rental Laptops",
    price: 1500,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "IIT Delhi",
    seller: "Laptop Hub",
    sellerId: 109,
    description: "Dell Inspiron 15 available for semester rental. Good condition, all accessories included.",
    rating: 4.7,
    reviews: 18,
    quantity: 1,
    postedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 10,
    title: "Lab Coat & Apron Set",
    category: "Lab Uniforms",
    price: 399,
    originalPrice: 499,
    image: "/placeholder.svg",
    college: "BITS Pilani",
    seller: "College Supplies",
    sellerId: 110,
    description: "Official lab coat and apron set. White, durable cotton material. Size M & L available.",
    rating: 4.6,
    reviews: 22,
    quantity: 1,
    postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 11,
    title: "Complete Stationery Bundle",
    category: "Stationery",
    price: 299,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "Delhi University",
    seller: "Stationery Store",
    sellerId: 111,
    description: "Bundle includes notebooks, pens, highlighters, and sticky notes. Perfect for semester.",
    rating: 4.5,
    reviews: 31,
    quantity: 1,
    postedAt: new Date(Date.now() - 30 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 12,
    title: "ID Card Holder & Tags",
    category: "ID Card Tags",
    price: 149,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "Ashoka University",
    seller: "Campus Essentials",
    sellerId: 112,
    description: "Durable ID card holders with name tags. Pack of 5. Waterproof and long-lasting.",
    rating: 4.4,
    reviews: 14,
    quantity: 1,
    postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 13,
    title: "Scientific Calculator",
    category: "Electronics",
    price: 899,
    originalPrice: 999,
    image: "/placeholder.svg",
    college: "NIT Bangalore",
    seller: "Tech Store",
    sellerId: 113,
    description: "Casio FX-991EX scientific calculator. Perfect for engineering and science students.",
    rating: 4.8,
    reviews: 26,
    quantity: 1,
    postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 14,
    title: "Microscope Slides Set",
    category: "Lab Equipment",
    price: 599,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "Delhi School of Economics",
    seller: "Lab Supplies",
    sellerId: 114,
    description: "Complete set of 50 microscope slides with cover slips. Unused and sealed.",
    rating: 4.7,
    reviews: 9,
    quantity: 1,
    postedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 15,
    title: "Wireless Earbuds",
    category: "Electronics",
    price: 1299,
    originalPrice: 1499,
    image: "/placeholder.svg",
    college: "St. Stephen's College",
    seller: "Electronics Hub",
    sellerId: 115,
    description: "Bluetooth 5.0 wireless earbuds with 20-hour battery life. Noise cancellation enabled.",
    rating: 4.6,
    reviews: 42,
    quantity: 1,
    postedAt: new Date(Date.now() - 9 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 16,
    title: "MacBook Pro - Rental",
    category: "Rental Laptops",
    price: 2500,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "IIT Bombay",
    seller: "Tech Rentals",
    sellerId: 116,
    description: "MacBook Pro 13-inch M1 available for semester rental. Perfect for coding and design.",
    rating: 4.9,
    reviews: 15,
    quantity: 1,
    postedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 17,
    title: "Basic Calculator",
    category: "Electronics",
    price: 199,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "Delhi University",
    seller: "Calc Shop",
    sellerId: 117,
    description: "Simple and reliable basic calculator for everyday use.",
    rating: 4.2,
    reviews: 8,
    quantity: 1,
    postedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 18,
    title: "Placeholder Item",
    category: "Stationery",
    price: 50,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "BITS Pilani",
    seller: "Generic Seller",
    sellerId: 118,
    description: "A placeholder item for testing purposes.",
    rating: 3.5,
    reviews: 2,
    quantity: 1,
    postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 19,
    title: "Organic Chemistry Reactions Notes",
    category: "Notes",
    price: 349,
    originalPrice: 0,
    image: "/placeholder.svg",
    college: "IIT Madras",
    seller: "Chem Notes",
    sellerId: 119,
    description: "Detailed notes on organic chemistry reactions and mechanisms.",
    rating: 4.6,
    reviews: 10,
    quantity: 1,
    postedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
  {
    id: 20,
    title: "Physics Concepts Textbook",
    category: "Books",
    price: 499,
    originalPrice: 599,
    image: "/placeholder.svg",
    college: "NIT Bangalore",
    seller: "Physics Books",
    sellerId: 120,
    description: "Comprehensive textbook covering key physics concepts.",
    rating: 4.7,
    reviews: 20,
    quantity: 1,
    postedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    images: ["/placeholder.svg"],
  },
]
