export const colleges = [
  "All Colleges",
  "IIT Delhi",
  "IIT Bombay",
  "IIT Madras",
  "Delhi University",
  "BITS Pilani",
  "NIT Bangalore",
  "Delhi School of Economics",
  "St. Stephen's College",
  "Ashoka University",
]

export const categories = [
  "All",
  "Notes",
  "Books",
  "Electronics",
  "Rental Laptops",
  "Lab Uniforms",
  "Stationery",
  "ID Card Tags",
  "Lab Equipment",
]

export const dummyItems = [
  {
    id: 1,
    title: "Advanced Calculus Notes",
    category: "Notes",
    price: 299,
    image: "/calculus-notes-textbook.jpg",
    college: "IIT Delhi",
    seller: "Raj Kumar",
    sellerId: 101,
    description:
      "Comprehensive calculus notes covering derivatives, integrals, and applications. Handwritten and well-organized.",
    rating: 4.5,
    reviews: 12,
  },
  {
    id: 2,
    title: "Physics Textbook - Mechanics",
    category: "Books",
    price: 450,
    image: "/physics-mechanics-textbook.jpg",
    college: "Delhi University",
    seller: "Priya Singh",
    sellerId: 102,
    description: "Original physics textbook focusing on mechanics. Minimal markings, in excellent condition.",
    rating: 4.8,
    reviews: 24,
  },
  {
    id: 3,
    title: "Organic Chemistry Study Guide",
    category: "Notes",
    price: 199,
    image: "/chemistry-organic-study-guide.jpg",
    college: "BITS Pilani",
    seller: "Aditya Patel",
    sellerId: 103,
    description: "Detailed study guide with reaction mechanisms and solved problems.",
    rating: 4.3,
    reviews: 8,
  },
  {
    id: 4,
    title: "Data Structures & Algorithms",
    category: "Books",
    price: 550,
    image: "/data-structures-algorithms-programming.jpg",
    college: "NIT Bangalore",
    seller: "Vikram Sharma",
    sellerId: 104,
    description: "Complete DSA book with C++ implementations and practice problems.",
    rating: 4.9,
    reviews: 35,
  },
  {
    id: 5,
    title: "Economics Principles Notes",
    category: "Notes",
    price: 249,
    image: "/economics-principles-microeconomics.jpg",
    college: "Delhi School of Economics",
    seller: "Neha Gupta",
    sellerId: 105,
    description: "Comprehensive notes on microeconomics and macroeconomics principles.",
    rating: 4.6,
    reviews: 15,
  },
  {
    id: 6,
    title: "English Literature - Shakespeare",
    category: "Books",
    price: 350,
    image: "/shakespeare-english-literature.jpg",
    college: "St. Stephen's College",
    seller: "Arjun Verma",
    sellerId: 106,
    description: "Annotated Shakespeare collection with critical analysis.",
    rating: 4.4,
    reviews: 11,
  },
  {
    id: 7,
    title: "Discrete Mathematics Complete Notes",
    category: "Notes",
    price: 279,
    image: "/discrete-mathematics-logic-sets.jpg",
    college: "IIT Bombay",
    seller: "Sneha Desai",
    sellerId: 107,
    description: "Complete discrete math notes with proofs and examples.",
    rating: 4.7,
    reviews: 19,
  },
  {
    id: 8,
    title: "Organic Chemistry Textbook",
    category: "Books",
    price: 520,
    image: "/organic-chemistry-textbook-reactions.jpg",
    college: "IIT Madras",
    seller: "Rohan Kapoor",
    sellerId: 108,
    description: "Advanced organic chemistry with reaction mechanisms and synthesis.",
    rating: 4.8,
    reviews: 28,
  },
  {
    id: 9,
    title: "Dell Laptop - Rental",
    category: "Rental Laptops",
    price: 1500,
    image: "/dell-laptop-computer.jpg",
    college: "IIT Delhi",
    seller: "Laptop Hub",
    sellerId: 109,
    description: "Dell Inspiron 15 available for semester rental. Good condition, all accessories included.",
    rating: 4.7,
    reviews: 18,
  },
  {
    id: 10,
    title: "Lab Coat & Apron Set",
    category: "Lab Uniforms",
    price: 399,
    image: "/lab-coat-apron-uniform.jpg",
    college: "BITS Pilani",
    seller: "College Supplies",
    sellerId: 110,
    description: "Official lab coat and apron set. White, durable cotton material. Size M & L available.",
    rating: 4.6,
    reviews: 22,
  },
  {
    id: 11,
    title: "Complete Stationery Bundle",
    category: "Stationery",
    price: 299,
    image: "/stationery-pens-notebooks.jpg",
    college: "Delhi University",
    seller: "Stationery Store",
    sellerId: 111,
    description: "Bundle includes notebooks, pens, highlighters, and sticky notes. Perfect for semester.",
    rating: 4.5,
    reviews: 31,
  },
  {
    id: 12,
    title: "ID Card Holder & Tags",
    category: "ID Card Tags",
    price: 149,
    image: "/id-card-holder-tags.jpg",
    college: "Ashoka University",
    seller: "Campus Essentials",
    sellerId: 112,
    description: "Durable ID card holders with name tags. Pack of 5. Waterproof and long-lasting.",
    rating: 4.4,
    reviews: 14,
  },
  {
    id: 13,
    title: "Scientific Calculator",
    category: "Electronics",
    price: 899,
    image: "/scientific-calculator.jpg",
    college: "NIT Bangalore",
    seller: "Tech Store",
    sellerId: 113,
    description: "Casio FX-991EX scientific calculator. Perfect for engineering and science students.",
    rating: 4.8,
    reviews: 26,
  },
  {
    id: 14,
    title: "Microscope Slides Set",
    category: "Lab Equipment",
    price: 599,
    image: "/microscope-slides-lab-equipment.jpg",
    college: "Delhi School of Economics",
    seller: "Lab Supplies",
    sellerId: 114,
    description: "Complete set of 50 microscope slides with cover slips. Unused and sealed.",
    rating: 4.7,
    reviews: 9,
  },
  {
    id: 15,
    title: "Wireless Earbuds",
    category: "Electronics",
    price: 1299,
    image: "/wireless-earbuds.png",
    college: "St. Stephen's College",
    seller: "Electronics Hub",
    sellerId: 115,
    description: "Bluetooth 5.0 wireless earbuds with 20-hour battery life. Noise cancellation enabled.",
    rating: 4.6,
    reviews: 42,
  },
  {
    id: 16,
    title: "MacBook Pro - Rental",
    category: "Rental Laptops",
    price: 2500,
    image: "/macbook-pro-laptop.png",
    college: "IIT Bombay",
    seller: "Tech Rentals",
    sellerId: 116,
    description: "MacBook Pro 13-inch M1 available for semester rental. Perfect for coding and design.",
    rating: 4.9,
    reviews: 15,
  },
]
